# Generated by Django 5.0.6 on 2024-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataExtractor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Time"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="User"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="x",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="X"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="y",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Y"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="z",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Z"
            ),
        ),
    ]
